name: Deploy_Code

on:
  workflow_dispatch:
    inputs:
      environment:
        description:  'deploy to'
        type: environment
        required: true

jobs:
  Deploy_Code:
    runs-on:  ubuntu-latest
    # if: ${{ inputs.environment }}
    env:
      DATABRICKS_WORKSPACE_URL: ${{ vars.URL }}
      TOKEN:  ${{ secrets.GIT_TOKEN }}
      ENVS: ${{ inputs.environment }}
      DB_Token: ${{ secrets.DB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v2


















